Support for waiting for status change signal.
mendersoftware/mender-shell pull request #26
Opened 2020-12-08 17:58 UTC by merlin-northern

Daemon now waits for the signal of auth status change.

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

2020-12-08 22:47 UTC, merlin-northern commented
@tranchitella [the last commit](https://github.com/mendersoftware/mender-shell/pull/26/commits/a30261e38638b638ad7e179524b5fc2e312f089d) brings a slight redesign of the daemon main loop and things around. I kept it separate in case you want to drop it, and keep the original structure.

2020-12-10 21:20 UTC, merlin-northern commented
@tranchitella there is one problem here, that I know of -- I will fix it in the next PR: if the device is accepted and mender-shell is started, then the wait for the auth token should not be performed, i.e.: on startup we can run onse GetJWTToken. ignore that, I will fix it.

2020-12-11 09:59 UTC, kacf requested changes

2020-12-11 09:59 UTC, kacf commented on client/dbus/dbus_libgio.go
> +				ParamData: "",
Why?

2020-12-11 09:59 UTC, kacf commented on client/dbus/dbus_libgio.go
> +				ParamData: "unsupported_type",
This seems wrong. Why use a valid type to represent in invalid type? Isn't it better to simply not add it, and log an error or something like that?

Or alternatively, use a dedicated type for invalid GVariants.

2020-12-11 09:59 UTC, kacf commented on app/daemon.go
> +			return p[0].ParamData.(string), nil
I'm not sure if this is correct. `waitForJWTToken` is called right after connecting to DBus, but this signal may not be broadcast again for days if the client is already authorized. mender-shell always needs call `GetJWTToken` first to see if the token already exists.

2020-12-11 09:59 UTC, kacf commented on app/daemon.go
> +					log.Debugf("dbusEventLoop: StateChanged form authorized to unauthorized." +
Minor: `s/form/from/`

2020-12-11 09:59 UTC, kacf commented on app/daemon.go
> +	go d.dbusEventLoop(client)
You are welcome to convince me otherwise, but I have some serious doubts about the thread safety of this function. You are assigning to, and Closing the connection, in several places inside this function, while the other function is also using it. Is `connection.Connection` really thread safe?

2020-12-11 09:59 UTC, kacf commented on app/daemon_test.go
> +				d.ws=tc.ws
This line inspired [this PR](https://github.com/mendersoftware/mendertesting/pull/122).

2020-12-11 10:00 UTC, kacf commented on app/daemon.go
> +			return p[0].ParamData.(string), nil
Ok, I see now that you already commented on this. I saw it to late, sorry. Just resolve this when it's fixed.

2020-12-11 10:10 UTC, merlin-northern commented on app/daemon.go
> +	go d.dbusEventLoop(client)
if you have doubts, then I will review the arch around that.
quick comment:
there is a mutex protecting the writes. the reads should be safe as they happen in one thread. closing and opening it is on purpose like that.

2020-12-11 10:12 UTC, merlin-northern commented on client/dbus/dbus_libgio.go
> +				ParamData: "",
I do not know:) basically this is to ensure that there is always something returned, so I do not have to worry about the array being empty. I will rework that.

2020-12-11 10:13 UTC, merlin-northern commented on client/dbus/dbus_libgio.go
> +				ParamData: "unsupported_type",
I wanted to explicitly point out that we got an unsupported type. I will rework that.

2020-12-11 10:27 UTC, kacf commented on app/daemon.go
> +	go d.dbusEventLoop(client)
But this mutex is not used inside the function. Does websocket explicitly say that it is thread safe to close a socket which is being written to or read from? Because if it doesn't, we should assume that it isn't.

2020-12-15 13:19 UTC, kacf requested changes

2020-12-15 13:19 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	//
Remove?

2020-12-15 13:19 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	defer handlersByTypeMutex.Unlock()
This is indeed much better, but there are still some remaining issues. See next comment.

2020-12-15 13:19 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
Unprotected access to `handlersByType`. Both reading and writing need to be mutex protected.

2020-12-15 13:19 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
Another unprotected access.

2020-12-15 13:19 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
And another.

2020-12-16 21:50 UTC, merlin-northern commented on client/dbus/dbus_libgio.go
> +				ParamData: "unsupported_type",
I removed that.

2020-12-16 21:50 UTC, merlin-northern commented on app/daemon.go
> +			return p[0].ParamData.(string), nil
this is fixed in this PR.

2020-12-16 21:50 UTC, merlin-northern commented on app/daemon.go
> +					log.Debugf("dbusEventLoop: StateChanged form authorized to unauthorized." +
fixed.

2020-12-16 21:51 UTC, merlin-northern commented on app/daemon.go
> +	go d.dbusEventLoop(client)
completely reworked.

2020-12-16 21:51 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
> +	//
sure!

2020-12-16 21:57 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
> +	defer handlersByTypeMutex.Unlock()
@kacf : you know what, there is a problem with that:
1. the framework does not support Read timeouts, so we *have* to wait in websocket Read for the messages, that means that Read is running most of the time
2. at the same time Writes must happen, and only the Writes must be protected (from the websocket point of view)
3. Close is used to actually break the Read wait, in case we run into some errors, or device is unauthorized

All of the above means that we cannot protect Read, Write and Close with the mutex that protects the hash. (I tried, but there is no way around it, thats how the websocket framework we use works)
However, this is not a problem, since the mutex is only about protecting handlersByType from concurrent Connect/Reconnect, and the way we use it in mender-shell should be ok.

2020-12-16 22:05 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
@kacf : you know what, there is a problem with that:

the framework does not support Read timeouts, so we have to wait in websocket Read for the messages, that means that Read is running most of the time
at the same time Writes must happen, and only the Writes must be protected (from the websocket point of view)
Close is used to actually break the Read wait, in case we run into some errors, or device is unauthorized
All of the above means that we cannot protect Read, Write and Close with the mutex that protects the hash. (I tried, but there is no way around it, thats how the websocket framework we use works)
However, this is not a problem, since the mutex is only about protecting handlersByType from concurrent Connect/Reconnect, and the way we use it in mender-shell should be ok.

2020-12-17 08:52 UTC, kacf requested changes

2020-12-17 08:52 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
Yes, but it's primarily the map I'm worried about here. You're right that `Read` and `Write` should be safe to call concurrently, and `Reconnect` always makes a new `ProtocolHandler` instance, so it should be safe as well (does not modify the original). As long as you have grabbed the member from the map, you don't need the mutex protection anymore.

So what you need to do is to add the lock, but release it after you have grabbed `h` from the map, and before you call `Read`. You might want to add a comment as well, that the reason for releasing the lock early is that `Read` may block for a long time.

2020-12-17 14:22 UTC, merlin-northern commented on app/daemon.go
> +				d.connected = true
thanks :) ok, I added a new channel, and redesigned again. even though I have my own opinion on atomicity of bool assignments.

2020-12-17 14:23 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
> +	h := handlersByType[proto]
right. fixed.

2020-12-17 14:57 UTC, kacf approved these changes

2020-12-17 14:57 UTC, kacf commented on connectionmanager/connectionmanager.go
> +	return h.connection.ReadMessage()
:+1:

2020-12-17 14:57 UTC, kacf commented on app/daemon.go
> +			response := <-d.connectionEstChan
Good, this looks safer! :+1:

2020-12-17 21:16 UTC, merged