Add mender-shell systemd service file
mendersoftware/mender-shell pull request #3
Opened 2020-11-05 12:36 UTC by oleorhagen

This fulfills the ticket MEN-4081.

Installs a simple systemd-service file with the same setup as the Mender-client.

Changelog: Add a systemd-service file to initialize the daemon on startup.

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2020-11-05 12:37 UTC, oleorhagen commented
I am not a 100% sure what is expected here, so I'm opening this as a baseline for discussion/guidance :)

2020-11-06 07:09 UTC, kacf requested changes
We should start thinking about a Makefile here, so that Yocto and the deb package can share install steps. This can be a separate PR though, I'm just mentioning it.

2020-11-06 07:09 UTC, kacf commented on support/mender-shell.service
> +After=systemd-resolved.service network-online.target
There should be a `Requires=mender-client.service` here, since it provides the authentication over DBus.

2020-11-06 08:26 UTC, oleorhagen commented on support/mender-shell.service
> +After=systemd-resolved.service network-online.target
No requires for DBus yet?
I left this out for the same reason it had no requires on `mender-client`: Is this supposed to be any more than a stand-in for now?

2020-11-06 09:05 UTC, oleorhagen commented on support/mender-shell.service
> +After=systemd-resolved.service network-online.target
> We should start thinking about a Makefile here, so that Yocto and the deb package can share install steps. This can be a separate PR though, I'm just mentioning it.

I'll add a `Makefile` as a part of: https://tracker.mender.io/browse/MEN-4083

2020-11-06 15:45 UTC, kacf commented on support/mender-shell.service
> +After=systemd-resolved.service network-online.target
> No requires for DBus yet?
> I left this out for the same reason it had no requires on `mender-client`: Is this supposed to be any more than a stand-in for now?

Not sure if I understood the question. Why not add what we know needs to be there?

I suppose we could add a Requires for DBus, but since systemd depends on DBus, I think it's redundant. Requires for the client is important however, since the client must start first, and mender-shell won't work without it. I believe you need both:

```
After=mender-client.service
Requires=mender-client.service
```

One defines start order, and the other defines dependency relationship.

2020-11-09 06:36 UTC, kacf approved these changes

2020-11-09 07:28 UTC, merged