Add a Makefile
mendersoftware/mender-shell pull request #7
Opened 2020-11-06 15:43 UTC by oleorhagen

And a `version` command to the `mender-shell`

2020-11-08 15:42 UTC, merlin-northern commented on config/version.go
> +// Copyright 2019 Northern.tech AS
perhaps 2020?

2020-11-08 15:45 UTC, merlin-northern commented on Makefile
> +	@gocyclo -over $(GOCYCLO) $(PKGFILES_notest)
we define $GO so maybe lets define gocyclo and the above two as well?

2020-11-08 15:45 UTC, merlin-northern submitted a review, later dismissed
lgtm. small comments, I trust you :)

2020-11-09 07:26 UTC, kacf requested changes

2020-11-09 07:26 UTC, kacf commented on Makefile
> +docexamplesdir ?= /usr/share/doc/mender-client/examples
Copy paste error.

2020-11-09 07:26 UTC, kacf commented on Makefile
> +.PHONY: check
`test` and `check` targets are missing. Just follow what the client does, I suppose?

2020-11-09 07:26 UTC, kacf commented on Makefile
> +uninstall: uninstall-bin uninstall-systemd
Both dependencies don't exist.

2020-11-09 07:26 UTC, kacf commented on config/version.go
> +	fmt.Printf(ShowVersion())
Should this be `Println` instead?

2020-11-09 08:18 UTC, kacf approved these changes

2020-11-09 08:19 UTC, merged